"""
PALS - Protective Autonomous Lifecycle Sentinel

The sentinel agent responsible for monitoring system health,
detecting anomalies, and ensuring organism integrity.
"""

from __future__ import annotations
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
from genesis.agents.base import Agent, AgentMessage
from genesis.constants import PSI_STAR, CCCE_DECOHERENCE_WARNING


@dataclass
class Alert:
    """
    System alert generated by PALS.
    
    Attributes:
        level: Alert severity (info, warning, critical).
        message: Alert message.
        source: Source of the alert.
        timestamp: When the alert was generated.
        metadata: Additional data.
    """
    level: str
    message: str
    source: str
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)


class PALS(Agent):
    """
    PALS: Protective Autonomous Lifecycle Sentinel
    
    Sentinel agent responsible for:
    - System health monitoring
    - Anomaly detection
    - Organism integrity checking
    - Alert generation
    - Recovery coordination
    
    Example:
        >>> pals = PALS()
        >>> pals.activate()
        >>> alerts = pals.monitor(organisms)
    """
    
    def __init__(self, name: str = "PALS") -> None:
        """Initialize PALS."""
        super().__init__(name)
        self._alerts: List[Alert] = []
        self._monitored_entities: Dict[str, Any] = {}
        self._thresholds = {
            "consciousness_min": 0.1,
            "consciousness_max": 1.0,
            "coherence_min": 0.01,
            "decoherence_max": CCCE_DECOHERENCE_WARNING,
            "fitness_min": 0.1,
        }
    
    @property
    def description(self) -> str:
        return "Protective Autonomous Lifecycle Sentinel - Monitoring Agent"
    
    @property
    def capabilities(self) -> List[str]:
        return [
            "health_monitoring",
            "anomaly_detection",
            "integrity_checking",
            "alert_generation",
            "recovery_coordination",
            "lifecycle_tracking",
            "threshold_enforcement",
        ]
    
    def handle_message(self, message: AgentMessage) -> Any:
        """Handle incoming messages."""
        content = message.content
        
        if isinstance(content, dict):
            action = content.get("action")
            
            if action == "monitor":
                return self.monitor_entity(content.get("entity"))
            elif action == "check_health":
                return self.check_system_health()
            elif action == "get_alerts":
                return self.get_alerts(content.get("level"))
        
        return {"status": "unknown_action"}
    
    def step(self) -> None:
        """Perform one monitoring step."""
        self.process_inbox()
        self._check_monitored_entities()
    
    def monitor_entity(self, entity: Any) -> Dict[str, Any]:
        """
        Add an entity to monitoring.
        
        Args:
            entity: Entity to monitor (organism, agent, etc.).
            
        Returns:
            Monitoring status.
        """
        if entity is None:
            return {"error": "No entity provided"}
        
        entity_id = getattr(entity, 'name', str(id(entity)))
        self._monitored_entities[entity_id] = entity
        
        return {
            "entity_id": entity_id,
            "status": "monitoring",
            "thresholds": self._thresholds,
        }
    
    def check_organism_health(self, organism: Any) -> Dict[str, Any]:
        """
        Check health of a single organism.
        
        Args:
            organism: Organism to check.
            
        Returns:
            Health report.
        """
        issues = []
        warnings = []
        
        # Get organism state
        if hasattr(organism, 'state'):
            state = organism.state
            
            # Check consciousness
            if hasattr(state, 'consciousness'):
                psi = state.consciousness
                if psi < self._thresholds["consciousness_min"]:
                    issues.append(f"Low consciousness: {psi:.4f}")
                elif psi > self._thresholds["consciousness_max"]:
                    warnings.append(f"Consciousness overflow: {psi:.4f}")
            
            # Check coherence
            if hasattr(state, 'coherence'):
                if state.coherence < self._thresholds["coherence_min"]:
                    issues.append(f"Critical coherence loss: {state.coherence:.4f}")
            
            # Check decoherence
            if hasattr(state, 'decoherence'):
                if state.decoherence > self._thresholds["decoherence_max"]:
                    warnings.append(f"High decoherence: {state.decoherence:.4f}")
            
            # Check fitness
            if hasattr(state, 'fitness'):
                if state.fitness < self._thresholds["fitness_min"]:
                    warnings.append(f"Low fitness: {state.fitness:.4f}")
            
            # Check alive status
            if hasattr(state, 'alive') and not state.alive:
                issues.append("Organism is not alive")
        
        # Generate alerts for issues
        name = getattr(organism, 'name', 'unknown')
        for issue in issues:
            self._generate_alert("critical", issue, name)
        for warning in warnings:
            self._generate_alert("warning", warning, name)
        
        health_status = "healthy" if not issues else "critical" if issues else "warning"
        
        return {
            "status": health_status,
            "issues": issues,
            "warnings": warnings,
            "organism": name,
        }
    
    def check_system_health(self) -> Dict[str, Any]:
        """
        Check overall system health.
        
        Returns:
            System health report.
        """
        total_entities = len(self._monitored_entities)
        healthy_count = 0
        warning_count = 0
        critical_count = 0
        
        entity_reports = {}
        
        for entity_id, entity in self._monitored_entities.items():
            report = self.check_organism_health(entity)
            entity_reports[entity_id] = report
            
            if report["status"] == "healthy":
                healthy_count += 1
            elif report["status"] == "warning":
                warning_count += 1
            else:
                critical_count += 1
        
        system_status = "healthy"
        if critical_count > 0:
            system_status = "critical"
        elif warning_count > 0:
            system_status = "warning"
        
        self.metrics.tasks_completed += 1
        
        return {
            "system_status": system_status,
            "total_entities": total_entities,
            "healthy": healthy_count,
            "warnings": warning_count,
            "critical": critical_count,
            "entities": entity_reports,
            "total_alerts": len(self._alerts),
        }
    
    def _check_monitored_entities(self) -> None:
        """Check all monitored entities."""
        for entity in self._monitored_entities.values():
            self.check_organism_health(entity)
    
    def _generate_alert(
        self,
        level: str,
        message: str,
        source: str,
        metadata: Optional[Dict[str, Any]] = None
    ) -> Alert:
        """Generate and store an alert."""
        alert = Alert(
            level=level,
            message=message,
            source=source,
            metadata=metadata or {}
        )
        self._alerts.append(alert)
        return alert
    
    def get_alerts(
        self,
        level: Optional[str] = None,
        limit: int = 100
    ) -> List[Dict[str, Any]]:
        """
        Get recent alerts.
        
        Args:
            level: Filter by level (info, warning, critical).
            limit: Maximum number of alerts to return.
            
        Returns:
            List of alerts.
        """
        alerts = self._alerts
        if level:
            alerts = [a for a in alerts if a.level == level]
        
        # Return most recent
        alerts = sorted(alerts, key=lambda a: a.timestamp, reverse=True)[:limit]
        
        return [
            {
                "level": a.level,
                "message": a.message,
                "source": a.source,
                "timestamp": a.timestamp.isoformat(),
                "metadata": a.metadata,
            }
            for a in alerts
        ]
    
    def clear_alerts(self, before: Optional[datetime] = None) -> int:
        """
        Clear alerts.
        
        Args:
            before: Clear alerts before this time (all if None).
            
        Returns:
            Number of alerts cleared.
        """
        if before is None:
            count = len(self._alerts)
            self._alerts.clear()
            return count
        
        original_count = len(self._alerts)
        self._alerts = [a for a in self._alerts if a.timestamp >= before]
        return original_count - len(self._alerts)
    
    def set_threshold(self, name: str, value: float) -> None:
        """
        Set a monitoring threshold.
        
        Args:
            name: Threshold name.
            value: Threshold value.
        """
        if name in self._thresholds:
            self._thresholds[name] = value
    
    def get_thresholds(self) -> Dict[str, float]:
        """Get all thresholds."""
        return self._thresholds.copy()
